global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'telegram-notifications'

receivers:
- name: 'telegram-notifications'
  telegram_configs:
  - bot_token: '@b22dccn384_bot'  # Thay bằng Bot Token của bạn
    chat_id: '7914218538:AAGMqr7jKC1qzbJQ-mMy-FMCoGFgAmpSuks'      # Thay bằng Chat ID của bạn
    send_resolved: true
    parse_mode: 'Markdown'
    message: "{{ range .Alerts }}*{{ .Annotations.summary }}*\n{{ .Annotations.description }}\n{{ end }}"

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']